[package]
name = "NES"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
bitflags = "1.2.1"

sdl2 = "0.35.2"
rand = "0.8.5"

[[bin]]
name = "nes_launcher"
path = "src/main.rs"